
// Mock data aligned with menuSchema { resId, itemId, name, category, isVeg }
// Flattened format for /bulk ingestion
const menus = [
  { resId: 561633, itemId: 1, name: "Margherita Pizza", category: "Pizza", isVeg: true },
  { resId: 561633, itemId: 2, name: "Veg Supreme", category: "Pizza", isVeg: true },
  { resId: 561633, itemId: 3, name: "Chicken Supreme", category: "Pizza", isVeg: false },
  { resId: 561633, itemId: 4, name: "Paneer Tikka Pizza", category: "Pizza", isVeg: true },
  { resId: 561633, itemId: 5, name: "Garlic Breadsticks", category: "Sides", isVeg: true },
  { resId: 561633, itemId: 6, name: "Cheese Garlic Bread", category: "Sides", isVeg: true },
  { resId: 561633, itemId: 7, name: "Veggie Delight", category: "Pizza", isVeg: true },
  { resId: 561633, itemId: 8, name: "Chicken Tikka Pizza", category: "Pizza", isVeg: false },
  { resId: 561633, itemId: 9, name: "Pepsi 500ml", category: "Beverage", isVeg: true },
  { resId: 561633, itemId: 10, name: "Chocolate Lava Cake", category: "Dessert", isVeg: true },

  { resId: 343703, itemId: 1, name: "Farmhouse Pizza", category: "Pizza", isVeg: true },
  { resId: 343703, itemId: 2, name: "Peppy Paneer", category: "Pizza", isVeg: true },
  { resId: 343703, itemId: 3, name: "Chicken Dominator", category: "Pizza", isVeg: false },
  { resId: 343703, itemId: 4, name: "Veg Extravaganza", category: "Pizza", isVeg: true },
  { resId: 343703, itemId: 5, name: "Garlic Bread", category: "Sides", isVeg: true },
  { resId: 343703, itemId: 6, name: "Stuffed Garlic Bread", category: "Sides", isVeg: true },
  { resId: 343703, itemId: 7, name: "Chicken Wings", category: "Sides", isVeg: false },
  { resId: 343703, itemId: 8, name: "Zingy Parcel", category: "Sides", isVeg: true },
  { resId: 343703, itemId: 9, name: "Coke 600ml", category: "Beverage", isVeg: true },
  { resId: 343703, itemId: 10, name: "Choco Lava Cake", category: "Dessert", isVeg: true },

  { resId: 452429, itemId: 1, name: "Steamed Chicken Momo", category: "Chinese", isVeg: false },
  { resId: 452429, itemId: 2, name: "Fried Veg Momo", category: "Chinese", isVeg: true },
  { resId: 452429, itemId: 3, name: "Paneer Momo", category: "Chinese", isVeg: true },
  { resId: 452429, itemId: 4, name: "Chicken Cheese Momo", category: "Chinese", isVeg: false },
  { resId: 452429, itemId: 5, name: "Veg Hakka Noodles", category: "Chinese", isVeg: true },
  { resId: 452429, itemId: 6, name: "Chicken Fried Rice", category: "Chinese", isVeg: false },
  { resId: 452429, itemId: 7, name: "Chilli Paneer", category: "Chinese", isVeg: true },
  { resId: 452429, itemId: 8, name: "Spring Rolls", category: "Chinese", isVeg: true },
  { resId: 452429, itemId: 9, name: "Cold Coffee", category: "Beverage", isVeg: true },
  { resId: 452429, itemId: 10, name: "Iced Tea", category: "Beverage", isVeg: true },

  { resId: 659678, itemId: 1, name: "Chicken Tikka", category: "Tandoor", isVeg: false },
  { resId: 659678, itemId: 2, name: "Paneer Tikka", category: "Tandoor", isVeg: true },
  { resId: 659678, itemId: 3, name: "Mutton Seekh Kebab", category: "Tandoor", isVeg: false },
  { resId: 659678, itemId: 4, name: "Grilled Fish", category: "Tandoor", isVeg: false },
  { resId: 659678, itemId: 5, name: "Butter Chicken", category: "Indian Main", isVeg: false },
  { resId: 659678, itemId: 6, name: "Dal Makhani", category: "Indian Main", isVeg: true },
  { resId: 659678, itemId: 7, name: "Veg Biryani", category: "Biryani", isVeg: true },
  { resId: 659678, itemId: 8, name: "Chicken Biryani", category: "Biryani", isVeg: false },
  { resId: 659678, itemId: 9, name: "Gulab Jamun", category: "Dessert", isVeg: true },
  { resId: 659678, itemId: 10, name: "Ice Cream", category: "Dessert", isVeg: true },

  { resId: 89396, itemId: 1, name: "Brownie Sundae", category: "Dessert", isVeg: true },
  { resId: 89396, itemId: 2, name: "Chocolate Shake", category: "Beverage", isVeg: true },
  { resId: 89396, itemId: 3, name: "Strawberry Ice Cream", category: "Dessert", isVeg: true },
  { resId: 89396, itemId: 4, name: "Veg Burger", category: "Burger", isVeg: true },
  { resId: 89396, itemId: 5, name: "Chicken Burger", category: "Burger", isVeg: false },
  { resId: 89396, itemId: 6, name: "French Fries", category: "Sides", isVeg: true },
  { resId: 89396, itemId: 7, name: "Cold Coffee", category: "Beverage", isVeg: true },
  { resId: 89396, itemId: 8, name: "Cheese Sandwich", category: "Sandwich", isVeg: true },
  { resId: 89396, itemId: 9, name: "Vanilla Shake", category: "Beverage", isVeg: true },
  { resId: 89396, itemId: 10, name: "Belgian Waffle", category: "Dessert", isVeg: true },

  { resId: 78026, itemId: 1, name: "Chicken Shawarma", category: "Shawarma", isVeg: false },
  { resId: 78026, itemId: 2, name: "Beef Shawarma", category: "Shawarma", isVeg: false },
  { resId: 78026, itemId: 3, name: "Chicken Fried Rice", category: "Chinese", isVeg: false },
  { resId: 78026, itemId: 4, name: "Gobi Manchurian", category: "Chinese", isVeg: true },
  { resId: 78026, itemId: 5, name: "Chicken Noodles", category: "Chinese", isVeg: false },
  { resId: 78026, itemId: 6, name: "Grilled Chicken", category: "Grill", isVeg: false },
  { resId: 78026, itemId: 7, name: "Falooda", category: "Dessert", isVeg: true },
  { resId: 78026, itemId: 8, name: "Fresh Lime Soda", category: "Beverage", isVeg: true },
  { resId: 78026, itemId: 9, name: "Porotta & Beef", category: "Indian Main", isVeg: false },
  { resId: 78026, itemId: 10, name: "Veg Roll", category: "Snacks", isVeg: true },

  { resId: 380820, itemId: 1, name: "Kerala Meals", category: "Kerala Meals", isVeg: true },
  { resId: 380820, itemId: 2, name: "Chicken Biryani", category: "Biryani", isVeg: false },
  { resId: 380820, itemId: 3, name: "Beef Fry", category: "Kerala Main", isVeg: false },
  { resId: 380820, itemId: 4, name: "Fish Curry", category: "Kerala Main", isVeg: false },
  { resId: 380820, itemId: 5, name: "Veg Curry Meals", category: "Kerala Meals", isVeg: true },
  { resId: 380820, itemId: 6, name: "Porotta & Chicken Curry", category: "Kerala Main", isVeg: false },
  { resId: 380820, itemId: 7, name: "Chilli Chicken", category: "Chinese", isVeg: false },
  { resId: 380820, itemId: 8, name: "Fried Rice", category: "Chinese", isVeg: true },
  { resId: 380820, itemId: 9, name: "Lime Juice", category: "Beverage", isVeg: true },
  { resId: 380820, itemId: 10, name: "Ice Cream", category: "Dessert", isVeg: true },

  { resId: 113322, itemId: 1, name: "Masala Dosa", category: "South Indian", isVeg: true },
  { resId: 113322, itemId: 2, name: "Plain Dosa", category: "South Indian", isVeg: true },
  { resId: 113322, itemId: 3, name: "Idli Sambar", category: "South Indian", isVeg: true },
  { resId: 113322, itemId: 4, name: "Poori Bhaji", category: "South Indian", isVeg: true },
  { resId: 113322, itemId: 5, name: "Veg Meals", category: "South Indian", isVeg: true },
  { resId: 113322, itemId: 6, name: "Upma", category: "South Indian", isVeg: true },
  { resId: 113322, itemId: 7, name: "Vada", category: "South Indian", isVeg: true },
  { resId: 113322, itemId: 8, name: "Fresh Lime Juice", category: "Beverage", isVeg: true },
  { resId: 113322, itemId: 9, name: "Filter Coffee", category: "Beverage", isVeg: true },
  { resId: 113322, itemId: 10, name: "Payasam", category: "Dessert", isVeg: true },

 
];

module.exports = menus;
